/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ChannelPartnerRouteImport } from './routes/channel-partner'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as MediaRouteImport } from './routes/media'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as QhesPolicyRouteImport } from './routes/qhes-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerticalsRouteImport } from './routes/verticals'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ProjectsElixirRouteImport } from './routes/projects.elixir'
import { Route as ServicesBuildersRouteImport } from './routes/services.builders'
import { Route as ServicesConstructionRouteImport } from './routes/services.construction'
import { Route as ServicesInteriorRouteImport } from './routes/services.interior'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelPartnerRoute = ChannelPartnerRouteImport.update({
  id: '/channel-partner',
  path: '/channel-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const QhesPolicyRoute = QhesPolicyRouteImport.update({
  id: '/qhes-policy',
  path: '/qhes-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerticalsRoute = VerticalsRouteImport.update({
  id: '/verticals',
  path: '/verticals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ProjectsElixirRoute = ProjectsElixirRouteImport.update({
  id: '/elixir',
  path: '/elixir',
  getParentRoute: () => ProjectsRoute,
} as any)
const ServicesBuildersRoute = ServicesBuildersRouteImport.update({
  id: '/services/builders',
  path: '/services/builders',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesConstructionRoute = ServicesConstructionRouteImport.update({
  id: '/services/construction',
  path: '/services/construction',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesInteriorRoute = ServicesInteriorRouteImport.update({
  id: '/services/interior',
  path: '/services/interior',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/channel-partner': typeof ChannelPartnerRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/media': typeof MediaRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/qhes-policy': typeof QhesPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/verticals': typeof VerticalsRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/elixir': typeof ProjectsElixirRoute
  '/services/builders': typeof ServicesBuildersRoute
  '/services/construction': typeof ServicesConstructionRoute
  '/services/interior': typeof ServicesInteriorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/channel-partner': typeof ChannelPartnerRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/media': typeof MediaRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/qhes-policy': typeof QhesPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/verticals': typeof VerticalsRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/elixir': typeof ProjectsElixirRoute
  '/services/builders': typeof ServicesBuildersRoute
  '/services/construction': typeof ServicesConstructionRoute
  '/services/interior': typeof ServicesInteriorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/channel-partner': typeof ChannelPartnerRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/media': typeof MediaRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/qhes-policy': typeof QhesPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/verticals': typeof VerticalsRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/elixir': typeof ProjectsElixirRoute
  '/services/builders': typeof ServicesBuildersRoute
  '/services/construction': typeof ServicesConstructionRoute
  '/services/interior': typeof ServicesInteriorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/channel-partner'
    | '/contact'
    | '/gallery'
    | '/media'
    | '/privacy'
    | '/projects'
    | '/qhes-policy'
    | '/refund-policy'
    | '/sustainability'
    | '/terms'
    | '/verticals'
    | '/api/chat'
    | '/blog/$slug'
    | '/projects/elixir'
    | '/services/builders'
    | '/services/construction'
    | '/services/interior'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/channel-partner'
    | '/contact'
    | '/gallery'
    | '/media'
    | '/privacy'
    | '/projects'
    | '/qhes-policy'
    | '/refund-policy'
    | '/sustainability'
    | '/terms'
    | '/verticals'
    | '/api/chat'
    | '/blog/$slug'
    | '/projects/elixir'
    | '/services/builders'
    | '/services/construction'
    | '/services/interior'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/channel-partner'
    | '/contact'
    | '/gallery'
    | '/media'
    | '/privacy'
    | '/projects'
    | '/qhes-policy'
    | '/refund-policy'
    | '/sustainability'
    | '/terms'
    | '/verticals'
    | '/api/chat'
    | '/blog/$slug'
    | '/projects/elixir'
    | '/services/builders'
    | '/services/construction'
    | '/services/interior'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRoute
  ChannelPartnerRoute: typeof ChannelPartnerRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  MediaRoute: typeof MediaRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  QhesPolicyRoute: typeof QhesPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TermsRoute: typeof TermsRoute
  VerticalsRoute: typeof VerticalsRoute
  ApiChatRoute: typeof ApiChatRoute
  ServicesBuildersRoute: typeof ServicesBuildersRoute
  ServicesConstructionRoute: typeof ServicesConstructionRoute
  ServicesInteriorRoute: typeof ServicesInteriorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel-partner': {
      id: '/channel-partner'
      path: '/channel-partner'
      fullPath: '/channel-partner'
      preLoaderRoute: typeof ChannelPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qhes-policy': {
      id: '/qhes-policy'
      path: '/qhes-policy'
      fullPath: '/qhes-policy'
      preLoaderRoute: typeof QhesPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verticals': {
      id: '/verticals'
      path: '/verticals'
      fullPath: '/verticals'
      preLoaderRoute: typeof VerticalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/projects/elixir': {
      id: '/projects/elixir'
      path: '/elixir'
      fullPath: '/projects/elixir'
      preLoaderRoute: typeof ProjectsElixirRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/services/builders': {
      id: '/services/builders'
      path: '/services/builders'
      fullPath: '/services/builders'
      preLoaderRoute: typeof ServicesBuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/construction': {
      id: '/services/construction'
      path: '/services/construction'
      fullPath: '/services/construction'
      preLoaderRoute: typeof ServicesConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/interior': {
      id: '/services/interior'
      path: '/services/interior'
      fullPath: '/services/interior'
      preLoaderRoute: typeof ServicesInteriorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ProjectsRouteChildren {
  ProjectsElixirRoute: typeof ProjectsElixirRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsElixirRoute: ProjectsElixirRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRoute,
  ChannelPartnerRoute: ChannelPartnerRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  MediaRoute: MediaRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  QhesPolicyRoute: QhesPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SustainabilityRoute: SustainabilityRoute,
  TermsRoute: TermsRoute,
  VerticalsRoute: VerticalsRoute,
  ApiChatRoute: ApiChatRoute,
  ServicesBuildersRoute: ServicesBuildersRoute,
  ServicesConstructionRoute: ServicesConstructionRoute,
  ServicesInteriorRoute: ServicesInteriorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
